/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Time = IDL.Int;
export const Order = IDL.Record({
  'id' : IDL.Nat,
  'deliveryCharge' : IDL.Nat,
  'paymentMethod' : IDL.Text,
  'productIds' : IDL.Vec(IDL.Nat),
  'deliveryDate' : IDL.Text,
  'totalAmount' : IDL.Nat,
  'timestamp' : Time,
  'buyer' : IDL.Principal,
  'phone' : IDL.Text,
});
export const Product = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'stock' : IDL.Nat,
  'price' : IDL.Nat,
});

export const idlService = IDL.Service({
  'addProduct' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Nat, IDL.Nat],
      [IDL.Nat],
      [],
    ),
  'bulkAddProducts' : IDL.Func(
      [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Text, IDL.Nat, IDL.Nat))],
      [IDL.Vec(IDL.Nat)],
      [],
    ),
  'createOrder' : IDL.Func(
      [IDL.Vec(IDL.Nat), IDL.Text, IDL.Text, IDL.Nat, IDL.Text],
      [IDL.Nat],
      [],
    ),
  'getOrder' : IDL.Func([IDL.Nat], [IDL.Opt(Order)], ['query']),
  'getOrdersByBuyer' : IDL.Func([IDL.Principal], [IDL.Vec(Order)], ['query']),
  'getProduct' : IDL.Func([IDL.Nat], [IDL.Opt(Product)], ['query']),
  'getProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Time = IDL.Int;
  const Order = IDL.Record({
    'id' : IDL.Nat,
    'deliveryCharge' : IDL.Nat,
    'paymentMethod' : IDL.Text,
    'productIds' : IDL.Vec(IDL.Nat),
    'deliveryDate' : IDL.Text,
    'totalAmount' : IDL.Nat,
    'timestamp' : Time,
    'buyer' : IDL.Principal,
    'phone' : IDL.Text,
  });
  const Product = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'stock' : IDL.Nat,
    'price' : IDL.Nat,
  });
  
  return IDL.Service({
    'addProduct' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Nat, IDL.Nat],
        [IDL.Nat],
        [],
      ),
    'bulkAddProducts' : IDL.Func(
        [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Text, IDL.Nat, IDL.Nat))],
        [IDL.Vec(IDL.Nat)],
        [],
      ),
    'createOrder' : IDL.Func(
        [IDL.Vec(IDL.Nat), IDL.Text, IDL.Text, IDL.Nat, IDL.Text],
        [IDL.Nat],
        [],
      ),
    'getOrder' : IDL.Func([IDL.Nat], [IDL.Opt(Order)], ['query']),
    'getOrdersByBuyer' : IDL.Func([IDL.Principal], [IDL.Vec(Order)], ['query']),
    'getProduct' : IDL.Func([IDL.Nat], [IDL.Opt(Product)], ['query']),
    'getProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
  });
};

export const init = ({ IDL }) => { return []; };