/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Order {
  'id' : bigint,
  'deliveryCharge' : bigint,
  'paymentMethod' : string,
  'productIds' : Array<bigint>,
  'deliveryDate' : string,
  'totalAmount' : bigint,
  'timestamp' : Time,
  'buyer' : Principal,
  'phone' : string,
}
export interface Product {
  'id' : bigint,
  'name' : string,
  'description' : string,
  'stock' : bigint,
  'price' : bigint,
}
export type Time = bigint;
export interface _SERVICE {
  'addProduct' : ActorMethod<[string, string, bigint, bigint], bigint>,
  'bulkAddProducts' : ActorMethod<
    [Array<[string, string, bigint, bigint]>],
    Array<bigint>
  >,
  'createOrder' : ActorMethod<
    [Array<bigint>, string, string, bigint, string],
    bigint
  >,
  'getOrder' : ActorMethod<[bigint], [] | [Order]>,
  'getOrdersByBuyer' : ActorMethod<[Principal], Array<Order>>,
  'getProduct' : ActorMethod<[bigint], [] | [Product]>,
  'getProducts' : ActorMethod<[], Array<Product>>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];